-- BOLD_UPGRADE_CHECKPOINT_COVERED: true
-- BOLD_UPGRADE_STATEMENT_CHECKPOINT_VALIDATED: true
CREATE TABLE BOLDTC_BackUp (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ConfigurationData CLOB NOT NULL,
    PrivateKey CLOB NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL,
    IsActive NUMBER(1) NOT NULL
);