-- BOLD_UPGRADE_CHECKPOINT_COVERED: true
-- BOLD_UPGRADE_STATEMENT_CHECKPOINT_VALIDATED: true
ALTER TABLE BOLDTC_SystemSettings ADD SystemValue_Lob NCLOB;
UPDATE BOLDTC_SystemSettings SET SystemValue_Lob = TO_NCLOB(SystemValue);
ALTER TABLE BOLDTC_SystemSettings DROP COLUMN SystemValue;
ALTER TABLE BOLDTC_SystemSettings RENAME COLUMN SystemValue_Lob TO SystemValue;
